/* بيانات مشاريع الجرافيك — موقع رمضان قطب الجرافيك */
const PROJECTS_FALLBACK = [
  {
    "id": "alwaad-upvc-هوية-تجارية-414c5741",
    "discipline": "graphic",
    "category": "",
    "title": "ALWAAD UPVC — هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/02.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/1.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/3.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/4.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/6.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/7.webp"
    ],
    "video": "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/cover.mp4",
    "excerpt": "مشروع ALWAAD UPVC — هوية تجارية",
    "description": "مشروع ALWAAD UPVC — هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "aurion-x-born-from-imagination-41555249",
    "discipline": "graphic",
    "category": "",
    "title": "AURION X — Born from Imagination",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/AURION X — Born from Imagination/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/AURION X — Born from Imagination/cover.mp4",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (2).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (4).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (5).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (6).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (7).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (8).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02.webp"
    ],
    "video": "images/projects-by-name/graphic/AURION X — Born from Imagination/cover.mp4",
    "excerpt": "مشروع AURION X — Born from Imagination",
    "description": "مشروع AURION X — Born from Imagination.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "catalytic-ckean-air-هوية-تجارية-43415441",
    "discipline": "graphic",
    "category": "",
    "title": "CATALYTIC CKEAN AIR  - هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/03-photo.webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/1.webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (1).webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (2).webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (3).webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (5).webp"
    ],
    "video": "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/cover.mp4",
    "excerpt": "مشروع CATALYTIC CKEAN AIR  - هوية تجارية",
    "description": "مشروع CATALYTIC CKEAN AIR  - هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "dx-hardware-هوية-تجارية-44582048",
    "discipline": "graphic",
    "category": "",
    "title": "DX Hardware — هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/DX Hardware — هوية تجارية/01-cover (2).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (1).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (10).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (11).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (6).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (7).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (8).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (9).webp"
    ],
    "video": "images/projects-by-name/graphic/DX Hardware — هوية تجارية/cover.mp4",
    "excerpt": "مشروع DX Hardware — هوية تجارية",
    "description": "مشروع DX Hardware — هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-حملة-اعلانية-للصيانه-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC حملة اعلانية للصيانه",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/04-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/05-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/07-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/08-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/2.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC حملة اعلانية للصيانه",
    "description": "مشروع KOTB METAL UPVC حملة اعلانية للصيانه.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-حملة-اعلانيه-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC حملة اعلانيه",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/03-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/04-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/05-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/08-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/09-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/2.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC حملة اعلانيه",
    "description": "مشروع KOTB METAL UPVC حملة اعلانيه.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-سوشيال-ميديا-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC سوشيال ميديا",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/1.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/2.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/3.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/4.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/5.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/6.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/7.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC سوشيال ميديا",
    "description": "مشروع KOTB METAL UPVC سوشيال ميديا.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-هوية-تجارية-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC — هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/02.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/03-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/04-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/05-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/06-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/08-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/09-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/2.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC — هوية تجارية",
    "description": "مشروع KOTB METAL UPVC — هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "lecce-هوية-تجارية-4c454343",
    "discipline": "graphic",
    "category": "",
    "title": "LECCE-هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/LECCE-هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/LECCE-هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/02-photo.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/03-photo.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/1785424661761-019fb398-e16e-7eea-8d43-86000c97edb1.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/1785424798884-019fb39b-0571-7e31-9019-7ab815d874eb.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/1785425108422-019fb3a0-0448-77a2-afab-daba7db1744b.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/2.webp"
    ],
    "video": "images/projects-by-name/graphic/LECCE-هوية تجارية/cover.mp4",
    "excerpt": "مشروع LECCE-هوية تجارية",
    "description": "مشروع LECCE-هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-adidas-هوية-تجارية-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/05.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/1.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/2.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/3.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/4.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/6.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/7.webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-nike-lifestyle-mockups-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/02-photo.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/2.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/3.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/4.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/5.webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-nike-air-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- Nike Air",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (1).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (3).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (4).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (5).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (6).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (7).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (1).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (2).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (3).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (4).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (5).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (6).webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-nike-air-2-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- Nike Air 2",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (1).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (2).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (3).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (4).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1.webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air 2",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air 2.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "morgan-coffee-سوشيال-ميديا-4d6f7267",
    "discipline": "graphic",
    "category": "",
    "title": "Morgan Coffee — سوشيال ميديا",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/cover.mp4",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (1).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (2).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (3).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (4).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (5).webp"
    ],
    "video": "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/cover.mp4",
    "excerpt": "مشروع Morgan Coffee — سوشيال ميديا",
    "description": "مشروع Morgan Coffee — سوشيال ميديا.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "nike-milano-lifestyle-mockups-4e696b65",
    "discipline": "graphic",
    "category": "",
    "title": "Nike Milano — Lifestyle Mockups",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/cover.mp4",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/2.webp",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/3.webp",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/4.webp",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/5.webp"
    ],
    "video": "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/cover.mp4",
    "excerpt": "مشروع Nike Milano — Lifestyle Mockups",
    "description": "مشروع Nike Milano — Lifestyle Mockups.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "pharaohs-fc-شعار-وقميص-فريق-50686172",
    "discipline": "graphic",
    "category": "",
    "title": "Pharaohs FC — شعار وقميص فريق",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/cover.mp4",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/02-photo.webp",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/03-photo.webp",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/04-photo.webp",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/05-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/cover.mp4",
    "excerpt": "مشروع Pharaohs FC — شعار وقميص فريق",
    "description": "مشروع Pharaohs FC — شعار وقميص فريق.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "ألبوم-راب-الأدغال-cover-design-d8a3d984",
    "discipline": "graphic",
    "category": "",
    "title": "ألبوم راب الأدغال — Cover Design",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/cover.mp4",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/02-photo.webp",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/03-photo.webp",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/04-photo.webp",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/photo- (5).webp"
    ],
    "video": "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/cover.mp4",
    "excerpt": "مشروع ألبوم راب الأدغال — Cover Design",
    "description": "مشروع ألبوم راب الأدغال — Cover Design.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "إعلانات-السوشيال-ميديا-التعليمية-d8a5d8b9",
    "discipline": "graphic",
    "category": "",
    "title": "إعلانات السوشيال ميديا التعليمية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/cover.mp4",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/02-photo.webp",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/03-photo.webp",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/04-photo.webp",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/05-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/cover.mp4",
    "excerpt": "مشروع إعلانات السوشيال ميديا التعليمية",
    "description": "مشروع إعلانات السوشيال ميديا التعليمية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "تصميم-ابداعى-لمنتج-mahgoub-d8aad8b5",
    "discipline": "graphic",
    "category": "",
    "title": "تصميم ابداعى لمنتج-MAHGOUB",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/cover.mp4",
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/02-photo.webp",
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/03-photo.webp",
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/04-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/cover.mp4",
    "excerpt": "مشروع تصميم ابداعى لمنتج-MAHGOUB",
    "description": "مشروع تصميم ابداعى لمنتج-MAHGOUB.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "حكاية-الخبز-المصري-تصميم-هوية-وتغليف-منتج-d8add983",
    "discipline": "graphic",
    "category": "",
    "title": "حكاية الخبز المصري  تصميم هوية وتغليف منتج",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/cover.mp4",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/02-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/03-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/04-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/05-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/06-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/cover.mp4",
    "excerpt": "مشروع حكاية الخبز المصري  تصميم هوية وتغليف منتج",
    "description": "مشروع حكاية الخبز المصري  تصميم هوية وتغليف منتج.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "خيمة-وناسة-رمضان-2025-d8aed98a",
    "discipline": "graphic",
    "category": "",
    "title": "خيمة وناسة رمضان 2025",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/cover.mp4",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (1).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (2).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (3).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (4).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (5).webp"
    ],
    "video": "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/cover.mp4",
    "excerpt": "مشروع خيمة وناسة رمضان 2025",
    "description": "مشروع خيمة وناسة رمضان 2025.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "قائمة-أسعار-تراست-جروب-hp-d982d8a7",
    "discipline": "graphic",
    "category": "مطبوعات",
    "title": "قائمة أسعار تراست جروب — HP",
    "location": "القاهرة",
    "area": null,
    "year": "2025",
    "cover": "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/cover.mp4",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/02-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/03-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/04-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/05-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/06-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/07-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/cover.mp4",
    "excerpt": "تصميم قائمة أسعار احترافية بتنسيق واضح وسهل القراءة، مناسبة للطباعة أو المشاركة الرقمية.",
    "description": "تصميم قائمة أسعار احترافية بتنسيق واضح وسهل القراءة، مناسبة للطباعة أو المشاركة الرقمية.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطبوعات"
    ],
    "featured": false
  },
  {
    "id": "هوية-تجارية-المصرية-الهندسيه-upvc-d987d988",
    "discipline": "graphic",
    "category": "",
    "title": "هوية تجارية  المصرية الهندسيه UPVC",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/cover.mp4",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/02-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/03-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/04-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/05-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/06-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/cover.mp4",
    "excerpt": "مشروع هوية تجارية  المصرية الهندسيه UPVC",
    "description": "مشروع هوية تجارية  المصرية الهندسيه UPVC.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  }
];
const projectsData = PROJECTS_FALLBACK;
