/* الملف ده بيتولّد تلقائيًا من مجلدات المشاريع — متعدّلوش يدويًا. */
const PROJECTS_FALLBACK = [
  {
    "id": "بنزية-توتال-سمنود-d8a8d986",
    "discipline": "exterior",
    "category": "",
    "title": "بنزية توتال سمنود",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/exterior/بنزية توتال سمنود/cover.mp4",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (2).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (3).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (4).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (5).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (6).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (7).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (8).webp",
      "images/projects-by-name/exterior/بنزية توتال سمنود/بنزية توتال سمنود (9).webp"
    ],
    "video": "images/projects-by-name/exterior/بنزية توتال سمنود/cover.mp4",
    "excerpt": "مشروع بنزية توتال سمنود",
    "description": "مشروع بنزية توتال سمنود.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "alwaad-upvc-هوية-تجارية-414c5741",
    "discipline": "graphic",
    "category": "",
    "title": "ALWAAD UPVC — هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/02.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/1.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/3.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/4.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/6.webp",
      "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/7.webp"
    ],
    "video": "images/projects-by-name/graphic/ALWAAD UPVC — هوية تجارية/cover.mp4",
    "excerpt": "مشروع ALWAAD UPVC — هوية تجارية",
    "description": "مشروع ALWAAD UPVC — هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "aurion-x-born-from-imagination-41555249",
    "discipline": "graphic",
    "category": "",
    "title": "AURION X — Born from Imagination",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/AURION X — Born from Imagination/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/AURION X — Born from Imagination/cover.mp4",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (2).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (4).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (5).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (6).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (7).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02-photo (8).webp",
      "images/projects-by-name/graphic/AURION X — Born from Imagination/02.webp"
    ],
    "video": "images/projects-by-name/graphic/AURION X — Born from Imagination/cover.mp4",
    "excerpt": "مشروع AURION X — Born from Imagination",
    "description": "مشروع AURION X — Born from Imagination.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "catalytic-ckean-air-هوية-تجارية-43415441",
    "discipline": "graphic",
    "category": "",
    "title": "CATALYTIC CKEAN AIR  - هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/03-photo.webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/1.webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (1).webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (2).webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (3).webp",
      "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/PHOTO- (5).webp"
    ],
    "video": "images/projects-by-name/graphic/CATALYTIC CKEAN AIR  - هوية تجارية/cover.mp4",
    "excerpt": "مشروع CATALYTIC CKEAN AIR  - هوية تجارية",
    "description": "مشروع CATALYTIC CKEAN AIR  - هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "dx-hardware-هوية-تجارية-44582048",
    "discipline": "graphic",
    "category": "",
    "title": "DX Hardware — هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/DX Hardware — هوية تجارية/01-cover (2).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (1).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (10).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (11).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (6).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (7).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (8).webp",
      "images/projects-by-name/graphic/DX Hardware — هوية تجارية/PHOTO- (9).webp"
    ],
    "video": "images/projects-by-name/graphic/DX Hardware — هوية تجارية/cover.mp4",
    "excerpt": "مشروع DX Hardware — هوية تجارية",
    "description": "مشروع DX Hardware — هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-حملة-اعلانية-للصيانه-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC حملة اعلانية للصيانه",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/04-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/05-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/07-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/08-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/2.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانية للصيانه/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC حملة اعلانية للصيانه",
    "description": "مشروع KOTB METAL UPVC حملة اعلانية للصيانه.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-حملة-اعلانيه-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC حملة اعلانيه",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/03-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/04-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/05-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/08-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/09-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/2.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC حملة اعلانيه/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC حملة اعلانيه",
    "description": "مشروع KOTB METAL UPVC حملة اعلانيه.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-سوشيال-ميديا-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC سوشيال ميديا",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/1.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/2.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/3.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/4.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/5.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/6.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/7.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC سوشيال ميديا/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC سوشيال ميديا",
    "description": "مشروع KOTB METAL UPVC سوشيال ميديا.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "kotb-metal-upvc-هوية-تجارية-4b4f5442",
    "discipline": "graphic",
    "category": "",
    "title": "KOTB METAL UPVC — هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/02.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/03-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/04-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/05-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/06-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/08-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/09-photo.webp",
      "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/2.webp"
    ],
    "video": "images/projects-by-name/graphic/KOTB METAL UPVC — هوية تجارية/cover.mp4",
    "excerpt": "مشروع KOTB METAL UPVC — هوية تجارية",
    "description": "مشروع KOTB METAL UPVC — هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "lecce-هوية-تجارية-4c454343",
    "discipline": "graphic",
    "category": "",
    "title": "LECCE-هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/LECCE-هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/LECCE-هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/02-photo.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/03-photo.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/1785424661761-019fb398-e16e-7eea-8d43-86000c97edb1.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/1785424798884-019fb39b-0571-7e31-9019-7ab815d874eb.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/1785425108422-019fb3a0-0448-77a2-afab-daba7db1744b.webp",
      "images/projects-by-name/graphic/LECCE-هوية تجارية/2.webp"
    ],
    "video": "images/projects-by-name/graphic/LECCE-هوية تجارية/cover.mp4",
    "excerpt": "مشروع LECCE-هوية تجارية",
    "description": "مشروع LECCE-هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-adidas-هوية-تجارية-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/05.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/1.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/2.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/3.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/4.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/6.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/7.webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- ADIDAS - هوية تجارية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-nike-lifestyle-mockups-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/02-photo.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/2.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/3.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/4.webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/5.webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike - Lifestyle Mockups.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-nike-air-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- Nike Air",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (1).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (3).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (4).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (5).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (6).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo -  (7).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (1).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (2).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (3).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (4).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (5).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/photo-1 (6).webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "milano-footwear-industries-nike-air-2-4d494c41",
    "discipline": "graphic",
    "category": "",
    "title": "MILANO FOOTWEAR INDUSTRIES- Nike Air 2",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/cover.mp4",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (1).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (2).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (3).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1 (4).webp",
      "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/1.webp"
    ],
    "video": "images/projects-by-name/graphic/MILANO FOOTWEAR INDUSTRIES- Nike Air 2/cover.mp4",
    "excerpt": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air 2",
    "description": "مشروع MILANO FOOTWEAR INDUSTRIES- Nike Air 2.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "morgan-coffee-سوشيال-ميديا-4d6f7267",
    "discipline": "graphic",
    "category": "",
    "title": "Morgan Coffee — سوشيال ميديا",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/cover.mp4",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (1).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (2).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (3).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (4).webp",
      "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/1 (5).webp"
    ],
    "video": "images/projects-by-name/graphic/Morgan Coffee — سوشيال ميديا/cover.mp4",
    "excerpt": "مشروع Morgan Coffee — سوشيال ميديا",
    "description": "مشروع Morgan Coffee — سوشيال ميديا.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "nike-milano-lifestyle-mockups-4e696b65",
    "discipline": "graphic",
    "category": "",
    "title": "Nike Milano — Lifestyle Mockups",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/cover.mp4",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/2.webp",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/3.webp",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/4.webp",
      "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/5.webp"
    ],
    "video": "images/projects-by-name/graphic/Nike Milano — Lifestyle Mockups/cover.mp4",
    "excerpt": "مشروع Nike Milano — Lifestyle Mockups",
    "description": "مشروع Nike Milano — Lifestyle Mockups.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "pharaohs-fc-شعار-وقميص-فريق-50686172",
    "discipline": "graphic",
    "category": "",
    "title": "Pharaohs FC — شعار وقميص فريق",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/cover.mp4",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/02-photo.webp",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/03-photo.webp",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/04-photo.webp",
      "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/05-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/Pharaohs FC — شعار وقميص فريق/cover.mp4",
    "excerpt": "مشروع Pharaohs FC — شعار وقميص فريق",
    "description": "مشروع Pharaohs FC — شعار وقميص فريق.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "ألبوم-راب-الأدغال-cover-design-d8a3d984",
    "discipline": "graphic",
    "category": "",
    "title": "ألبوم راب الأدغال — Cover Design",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/cover.mp4",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/02-photo.webp",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/03-photo.webp",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/04-photo.webp",
      "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/photo- (5).webp"
    ],
    "video": "images/projects-by-name/graphic/ألبوم راب الأدغال — Cover Design/cover.mp4",
    "excerpt": "مشروع ألبوم راب الأدغال — Cover Design",
    "description": "مشروع ألبوم راب الأدغال — Cover Design.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "إعلانات-السوشيال-ميديا-التعليمية-d8a5d8b9",
    "discipline": "graphic",
    "category": "",
    "title": "إعلانات السوشيال ميديا التعليمية",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/cover.mp4",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/02-photo.webp",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/03-photo.webp",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/04-photo.webp",
      "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/05-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/إعلانات السوشيال ميديا التعليمية/cover.mp4",
    "excerpt": "مشروع إعلانات السوشيال ميديا التعليمية",
    "description": "مشروع إعلانات السوشيال ميديا التعليمية.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "تصميم-ابداعى-لمنتج-mahgoub-d8aad8b5",
    "discipline": "graphic",
    "category": "",
    "title": "تصميم ابداعى لمنتج-MAHGOUB",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/cover.mp4",
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/02-photo.webp",
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/03-photo.webp",
      "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/04-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/تصميم ابداعى لمنتج-MAHGOUB/cover.mp4",
    "excerpt": "مشروع تصميم ابداعى لمنتج-MAHGOUB",
    "description": "مشروع تصميم ابداعى لمنتج-MAHGOUB.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "حكاية-الخبز-المصري-تصميم-هوية-وتغليف-منتج-d8add983",
    "discipline": "graphic",
    "category": "",
    "title": "حكاية الخبز المصري  تصميم هوية وتغليف منتج",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/cover.mp4",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/02-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/03-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/04-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/05-photo.webp",
      "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/06-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/حكاية الخبز المصري  تصميم هوية وتغليف منتج/cover.mp4",
    "excerpt": "مشروع حكاية الخبز المصري  تصميم هوية وتغليف منتج",
    "description": "مشروع حكاية الخبز المصري  تصميم هوية وتغليف منتج.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "خيمة-وناسة-رمضان-2025-d8aed98a",
    "discipline": "graphic",
    "category": "",
    "title": "خيمة وناسة رمضان 2025",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/cover.mp4",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (1).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (2).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (3).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (4).webp",
      "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/1 (5).webp"
    ],
    "video": "images/projects-by-name/graphic/خيمة وناسة رمضان 2025/cover.mp4",
    "excerpt": "مشروع خيمة وناسة رمضان 2025",
    "description": "مشروع خيمة وناسة رمضان 2025.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "قائمة-أسعار-تراست-جروب-hp-d982d8a7",
    "discipline": "graphic",
    "category": "مطبوعات",
    "title": "قائمة أسعار تراست جروب — HP",
    "location": "القاهرة",
    "area": null,
    "year": "2025",
    "cover": "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/cover.mp4",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/02-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/03-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/04-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/05-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/06-photo.webp",
      "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/07-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/قائمة أسعار تراست جروب — HP/cover.mp4",
    "excerpt": "تصميم قائمة أسعار احترافية بتنسيق واضح وسهل القراءة، مناسبة للطباعة أو المشاركة الرقمية.",
    "description": "تصميم قائمة أسعار احترافية بتنسيق واضح وسهل القراءة، مناسبة للطباعة أو المشاركة الرقمية.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطبوعات"
    ],
    "featured": false
  },
  {
    "id": "هوية-تجارية-المصرية-الهندسيه-upvc-d987d988",
    "discipline": "graphic",
    "category": "",
    "title": "هوية تجارية  المصرية الهندسيه UPVC",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/cover.mp4",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/02-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/03-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/04-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/05-photo.webp",
      "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/06-photo.webp"
    ],
    "video": "images/projects-by-name/graphic/هوية تجارية  المصرية الهندسيه UPVC/cover.mp4",
    "excerpt": "مشروع هوية تجارية  المصرية الهندسيه UPVC",
    "description": "مشروع هوية تجارية  المصرية الهندسيه UPVC.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "حمام-عصري-d8add985",
    "discipline": "interior",
    "category": "",
    "title": "حمام عصري",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/حمام عصري/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/حمام عصري/cover.mp4",
      "images/projects-by-name/interior/حمام عصري/06-photo.webp",
      "images/projects-by-name/interior/حمام عصري/1.mp4",
      "images/projects-by-name/interior/حمام عصري/2.webp",
      "images/projects-by-name/interior/حمام عصري/20-photo.webp",
      "images/projects-by-name/interior/حمام عصري/3.webp"
    ],
    "video": "images/projects-by-name/interior/حمام عصري/cover.mp4",
    "excerpt": "مشروع حمام عصري",
    "description": "مشروع حمام عصري.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "حمام-ماستر-الاسكندريه-d8add985",
    "discipline": "interior",
    "category": "حمامات",
    "title": "حمام ماستر الاسكندريه",
    "location": "",
    "area": null,
    "year": "2025",
    "cover": "images/projects-by-name/interior/حمام ماستر الاسكندريه/حمام ماستر الاسكندريه (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/حمام ماستر الاسكندريه/cover.mp4",
      "images/projects-by-name/interior/حمام ماستر الاسكندريه/حمام ماستر الاسكندريه (2).webp",
      "images/projects-by-name/interior/حمام ماستر الاسكندريه/حمام ماستر الاسكندريه (3).webp"
    ],
    "video": "images/projects-by-name/interior/حمام ماستر الاسكندريه/cover.mp4",
    "excerpt": "تصميم حمام بخامات عصرية سهلة التنظيف، مع إضاءة هادئة تمنح المساحة إحساسًا فندقيًا مريحًا.",
    "description": "تصميم حمام بخامات عصرية سهلة التنظيف، مع إضاءة هادئة تمنح المساحة إحساسًا فندقيًا مريحًا.",
    "idea": "",
    "materials": [],
    "tags": [
      "حمامات"
    ],
    "featured": false
  },
  {
    "id": "حمام-ماستر-الدقى-d8add985",
    "discipline": "interior",
    "category": "",
    "title": "حمام ماستر الدقى",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/حمام ماستر الدقى/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/حمام ماستر الدقى/cover.mp4",
      "images/projects-by-name/interior/حمام ماستر الدقى/01-cover.mp4",
      "images/projects-by-name/interior/حمام ماستر الدقى/1.webp",
      "images/projects-by-name/interior/حمام ماستر الدقى/حمام ماستر عين الدقى (1).webp",
      "images/projects-by-name/interior/حمام ماستر الدقى/حمام ماستر عين الدقى (2).webp",
      "images/projects-by-name/interior/حمام ماستر الدقى/حمام ماستر عين الدقى (4).webp"
    ],
    "video": "images/projects-by-name/interior/حمام ماستر الدقى/cover.mp4",
    "excerpt": "مشروع حمام ماستر الدقى",
    "description": "مشروع حمام ماستر الدقى.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "ريبسشن-الشروق-d8b1d98a",
    "discipline": "interior",
    "category": "",
    "title": "ريبسشن الشروق",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/ريبسشن الشروق/ريبسشن الشروق (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/ريبسشن الشروق/cover.mp4"
    ],
    "video": "images/projects-by-name/interior/ريبسشن الشروق/cover.mp4",
    "excerpt": "مشروع ريبسشن الشروق",
    "description": "مشروع ريبسشن الشروق.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "ريسبشن-مطبخ-امريكا-مدينة-بدر-d8b1d98a",
    "discipline": "interior",
    "category": "",
    "title": "ريسبشن & مطبخ امريكا مدينة  بدر",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/ريسبشن & مطبخ امريكا مدينة  بدر/ريسبشن  مع مطبخ امريكا مدينة  بدر (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/ريسبشن & مطبخ امريكا مدينة  بدر/cover.mp4"
    ],
    "video": "images/projects-by-name/interior/ريسبشن & مطبخ امريكا مدينة  بدر/cover.mp4",
    "excerpt": "مشروع ريسبشن & مطبخ امريكا مدينة  بدر",
    "description": "مشروع ريسبشن & مطبخ امريكا مدينة  بدر.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "شقة-طنطا-d8b1d98a",
    "discipline": "interior",
    "category": "شقق سكنية",
    "title": "شقة طنطا",
    "location": "طنطا",
    "area": "80 م²",
    "year": "2023",
    "cover": "images/projects-by-name/interior/ريسبشن طنطا/ريسبشن طنطا (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/ريسبشن طنطا/ريسبشن طنطا (2).webp",
      "images/projects-by-name/interior/ريسبشن طنطا/ريسبشن طنطا (3).webp"
    ],
    "video": null,
    "excerpt": "شقة بمساحة 80 مترًا سُلّمت على المسطح، وكان الهدف تصميم صالة استقبال تجمع بين البساطة والدفء دون إثقال المساحة. اعتمدنا ",
    "description": "شقة بمساحة 80 مترًا سُلّمت على المسطح، وكان الهدف تصميم صالة استقبال تجمع بين البساطة والدفء دون إثقال المساحة. اعتمدنا على تناغم الألوان المحايدة، إضاءة مخفية بالأسقف الجبسية، وقطع أثاث مختارة بعناية لتمنح إحساسًا بالرحابة رغم المساحة المحدودة.",
    "idea": "الفكرة التصميمية قامت على تبسيط الخطوط وتوزيع الإضاءة بشكل يخلق طبقات بصرية هادئة، مع لوحات ديكورية هندسية تكسر رتابة الحائط الرئيسي وتمنح الصالة طابعًا مميزًا.",
    "materials": [
      "دهانات مطفية فاخرة",
      "أرضيات باركيه",
      "أسقف جبسية بإضاءة مخفية",
      "أثاث تنجيد قماش"
    ],
    "tags": [
      "صالة استقبال",
      "80 متر",
      "تسليم كامل"
    ],
    "featured": true
  },
  {
    "id": "شقة-عائلية-مدينة-بدر-d8b4d982",
    "discipline": "interior",
    "category": "شقق سكنية",
    "title": "شقة عائلية — مدينة بدر",
    "location": "مدينة بدر",
    "area": "80 م²",
    "year": "2024",
    "cover": "images/projects-by-name/interior/شقة عائلية — مدينة بدر/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/شقة عائلية — مدينة بدر/028-photo.webp",
      "images/projects-by-name/interior/شقة عائلية — مدينة بدر/18-photo.webp",
      "images/projects-by-name/interior/شقة عائلية — مدينة بدر/27-photo.webp"
    ],
    "video": null,
    "excerpt": "شقة بمساحة 80 مترًا سُلّمت على المسطح، وكان الهدف تصميم صالة استقبال تجمع بين البساطة والدفء دون إثقال المساحة. اعتمدنا ",
    "description": "شقة بمساحة 80 مترًا سُلّمت على المسطح، وكان الهدف تصميم صالة استقبال تجمع بين البساطة والدفء دون إثقال المساحة. اعتمدنا على تناغم الألوان المحايدة، إضاءة مخفية بالأسقف الجبسية، وقطع أثاث مختارة بعناية لتمنح إحساسًا بالرحابة رغم المساحة المحدودة.",
    "idea": "الفكرة التصميمية قامت على تبسيط الخطوط وتوزيع الإضاءة بشكل يخلق طبقات بصرية هادئة، مع لوحات ديكورية هندسية تكسر رتابة الحائط الرئيسي وتمنح الصالة طابعًا مميزًا.",
    "materials": [
      "دهانات مطفية فاخرة",
      "أرضيات باركيه",
      "أسقف جبسية بإضاءة مخفية",
      "أثاث تنجيد قماش"
    ],
    "tags": [
      "صالة استقبال",
      "80 متر",
      "تسليم كامل"
    ],
    "featured": true
  },
  {
    "id": "شقة-عصرية-الشروق-d8b4d982",
    "discipline": "interior",
    "category": "شقق سكنية",
    "title": "شقة عصرية — الشروق",
    "location": "الشروق",
    "area": "120 م²",
    "year": "2024",
    "cover": "images/projects-by-name/interior/شقة عصرية — الشروق/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/شقة عصرية — الشروق/1 (1).webp",
      "images/projects-by-name/interior/شقة عصرية — الشروق/1 (2).webp"
    ],
    "video": null,
    "excerpt": "مشروع بمساحة 120 مترًا في الشروق تضمن تصميم صالة معيشة متصلة بركن السفرة. اخترنا لوحة ألوان داكنة هادئة تعكس ذوقًا رصينً",
    "description": "مشروع بمساحة 120 مترًا في الشروق تضمن تصميم صالة معيشة متصلة بركن السفرة. اخترنا لوحة ألوان داكنة هادئة تعكس ذوقًا رصينًا، مع تفاصيل إضاءة معلّقة فوق طاولة السفرة تمنح المكان طابعًا احتفاليًا في المناسبات العائلية.",
    "idea": "التصميم يعتمد على الفصل البصري بين منطقتي الجلوس والسفرة عبر اختلاف الإضاءة ودرجات اللون، مع الحفاظ على تدفق بصري واحد يجمع المساحتين في مشهد متكامل.",
    "materials": [
      "وحدات عرض خشبية بإضاءة داخلية",
      "سجاد صوف كثيف",
      "إضاءة معلّقة",
      "رخام طبيعي للأرضيات"
    ],
    "tags": [
      "معيشة وسفرة",
      "120 متر",
      "تسليم كامل"
    ],
    "featured": false
  },
  {
    "id": "شقة-معاصرة-جسر-السويس-d8b4d982",
    "discipline": "interior",
    "category": "",
    "title": "شقة معاصرة — جسر السويس",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/شقة معاصرة — جسر السويس/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/شقة معاصرة — جسر السويس/1.mp4"
    ],
    "video": "images/projects-by-name/interior/شقة معاصرة — جسر السويس/1.mp4",
    "excerpt": "مشروع شقة معاصرة — جسر السويس",
    "description": "مشروع شقة معاصرة — جسر السويس.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "صالة-استقبال-بسيطة-عين-شمس-d8b5d8a7",
    "discipline": "interior",
    "category": "شقق سكنية",
    "title": "صالة استقبال بسيطة — عين شمس",
    "location": "عين شمس",
    "area": "100 م²",
    "year": "2023",
    "cover": "images/projects-by-name/interior/صالة استقبال بسيطة — عين شمس/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/صالة استقبال بسيطة — عين شمس/1 (3).webp",
      "images/projects-by-name/interior/صالة استقبال بسيطة — عين شمس/1 (4).webp",
      "images/projects-by-name/interior/صالة استقبال بسيطة — عين شمس/1 (5).webp"
    ],
    "video": null,
    "excerpt": "مشروع بمساحة 100 متر ركّز على تبسيط عناصر الصالة إلى أقصى درجة، مع وحدة تلفزيون بيضاء معلّقة ورفوف عرض مفتوحة، لتظل المس",
    "description": "مشروع بمساحة 100 متر ركّز على تبسيط عناصر الصالة إلى أقصى درجة، مع وحدة تلفزيون بيضاء معلّقة ورفوف عرض مفتوحة، لتظل المساحة مريحة بصريًا وسهلة الصيانة يوميًا.",
    "idea": "الاعتماد على الألوان الفاتحة والخطوط المستقيمة يمنح المساحة اتساعًا بصريًا، بينما تضيف الإضاءة الدائرية المعلّقة لمسة عصرية مميزة لسقف الصالة.",
    "materials": [
      "وحدات معلّقة بديكور أبيض",
      "دهانات فاتحة",
      "إضاءة معلّقة دائرية",
      "نباتات ديكورية"
    ],
    "tags": [
      "صالة استقبال",
      "100 متر",
      "تسليم كامل"
    ],
    "featured": false
  },
  {
    "id": "صالة-بروح-لونية-جريئة-العباسية-d8b5d8a7",
    "discipline": "interior",
    "category": "شقق سكنية",
    "title": "صالة بروح لونية جريئة — العباسية",
    "location": "العباسية",
    "area": "80 م²",
    "year": "2022",
    "cover": "images/projects-by-name/interior/صالة بروح لونية جريئة — العباسية/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/صالة بروح لونية جريئة — العباسية/1 (1).webp",
      "images/projects-by-name/interior/صالة بروح لونية جريئة — العباسية/1 (2).webp",
      "images/projects-by-name/interior/صالة بروح لونية جريئة — العباسية/1 (4).webp"
    ],
    "video": null,
    "excerpt": "شقة بمساحة 80 مترًا اخترنا لها لغة لونية أكثر جرأة، بحائط تركواز مقسّم بمنحنيات جبسية وقطع أثاث زرقاء ونحاسية، لتتحول ال",
    "description": "شقة بمساحة 80 مترًا اخترنا لها لغة لونية أكثر جرأة، بحائط تركواز مقسّم بمنحنيات جبسية وقطع أثاث زرقاء ونحاسية، لتتحول المساحة الصغيرة إلى صالة مفعمة بالشخصية دون أن تفقد اتزانها.",
    "idea": "الفكرة هنا معاكسة لبقية المشاريع الهادئة: استخدام اللون كعنصر تصميمي رئيسي، مع ضبط باقي العناصر (الأرضيات، الستائر) بدرجات محايدة لتبقى الجرأة اللونية متحكّمًا فيها.",
    "materials": [
      "دهانات تركواز",
      "تنجيد قماش ملوّن",
      "تفاصيل نحاسية",
      "إضاءة مخفية منحنية"
    ],
    "tags": [
      "صالة استقبال",
      "80 متر",
      "تسليم كامل"
    ],
    "featured": false
  },
  {
    "id": "غرفة-أطفال-العاشر-من-رمضان-d8bad8b1",
    "discipline": "interior",
    "category": "",
    "title": "غرفة أطفال - العاشر من رمضان",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/غرفة أطفال - العاشر من رمضان/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/غرفة أطفال - العاشر من رمضان/1.mp4"
    ],
    "video": "images/projects-by-name/interior/غرفة أطفال - العاشر من رمضان/1.mp4",
    "excerpt": "مشروع غرفة أطفال - العاشر من رمضان",
    "description": "مشروع غرفة أطفال - العاشر من رمضان.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "غرفة-نوم-رئيسية-شبابي-d8bad8b1",
    "discipline": "interior",
    "category": "",
    "title": "غرفة نوم رئيسية  شبابي",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/غرفة نوم رئيسية  شبابي/01-cover.webp",
    "before": null,
    "gallery": [],
    "video": null,
    "excerpt": "مشروع غرفة نوم رئيسية  شبابي",
    "description": "مشروع غرفة نوم رئيسية  شبابي.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "غرفة-نوم-ماستر-بنها-d8bad8b1",
    "discipline": "interior",
    "category": "",
    "title": "غرفة نوم ماستر - بنها",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/غرفة نوم ماستر - بنها/01-cover.webp",
    "before": null,
    "gallery": [],
    "video": null,
    "excerpt": "مشروع غرفة نوم ماستر - بنها",
    "description": "مشروع غرفة نوم ماستر - بنها.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "غرفة-نوم-ماستر-الرحاب-d8bad8b1",
    "discipline": "interior",
    "category": "غرف نوم",
    "title": "غرفة نوم ماستر— الرحاب",
    "location": "الرحاب",
    "area": "150 م²",
    "year": "2025",
    "cover": "images/projects-by-name/interior/غرفة نوم ماستر الرحاب/غرفة نوم ماستر الرحاب (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/غرفة نوم ماستر الرحاب/غرفة نوم ماستر الرحاب (2).webp"
    ],
    "video": null,
    "excerpt": "غرفة نوم رئيسية ضمن شقة بمساحة 150 مترًا، صُممت بلمسة كلاسيكية معاصرة تجمع بين الخشب الداكن والتفاصيل الذهبية الخفيفة. ط",
    "description": "غرفة نوم رئيسية ضمن شقة بمساحة 150 مترًا، صُممت بلمسة كلاسيكية معاصرة تجمع بين الخشب الداكن والتفاصيل الذهبية الخفيفة. طاولة تسريحة مطلة على النافذة، وستائر مزدوجة تمنح الغرفة خصوصية وإحساسًا فندقيًا.",
    "idea": "التصميم يوازن بين الطابع الكلاسيكي في القطع الخشبية المفرّغة والإحساس المعاصر في اختيار الألوان الترابية والإضاءة المخفية أعلى تجهيزة السرير.",
    "materials": [
      "خشب زان مصمت",
      "قماش مخمل للستائر",
      "أرضيات باركيه",
      "إضاءة مخفية علوية"
    ],
    "tags": [
      "غرفة نوم",
      "150 متر",
      "تسليم كامل"
    ],
    "featured": true
  },
  {
    "id": "غرفة-نوم-ومعيشة-التجمع-d8bad8b1",
    "discipline": "interior",
    "category": "",
    "title": "غرفة نوم ومعيشة التجمع",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/غرفة نوم ومعيشة التجمع/غرفة نوم ومعيشة التجمع (5).webp",
    "before": null,
    "gallery": [],
    "video": null,
    "excerpt": "مشروع غرفة نوم ومعيشة التجمع",
    "description": "مشروع غرفة نوم ومعيشة التجمع.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "كتالوج-حمام-ماستر-d983d8aa",
    "discipline": "interior",
    "category": "",
    "title": "كتالوج حمام ماستر",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/كتالوج حمام ماستر/حمام ماستر  (1).webp",
    "before": null,
    "gallery": [],
    "video": null,
    "excerpt": "مشروع كتالوج حمام ماستر",
    "description": "مشروع كتالوج حمام ماستر.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "كيدز-أريا-السعوديه-d983d98a",
    "discipline": "interior",
    "category": "",
    "title": "كيدز أريا السعوديه",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/كيدز أريا السعوديه/01-cover.webp",
    "before": null,
    "gallery": [],
    "video": null,
    "excerpt": "مشروع كيدز أريا السعوديه",
    "description": "مشروع كيدز أريا السعوديه.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "مطبخ-كلاسيك-d985d8b7",
    "discipline": "interior",
    "category": "مطابخ",
    "title": "مطبخ كلاسيك",
    "location": "",
    "area": null,
    "year": "2026",
    "cover": "images/projects-by-name/interior/مطبخ  نيو مودرن/03-photo.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مطبخ  نيو مودرن/09-photo.webp",
      "images/projects-by-name/interior/مطبخ  نيو مودرن/10-photo.webp"
    ],
    "video": null,
    "excerpt": "تصميم مطبخ بطابع كلاسيك - بخطوط بسيطة ووحدات عملية تناسب الاستخدام اليومي.",
    "description": "تصميم مطبخ بطابع كلاسيك - بخطوط بسيطة ووحدات عملية تناسب الاستخدام اليومي.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطابخ",
      "Modern Kitchen"
    ],
    "featured": false
  },
  {
    "id": "مطبخ-الشروق-d985d8b7",
    "discipline": "interior",
    "category": "مطابخ",
    "title": "مطبخ الشروق",
    "location": "الشروق",
    "area": null,
    "year": "2025",
    "cover": "images/projects-by-name/interior/مطبخ -  الشروق/12-photo (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مطبخ -  الشروق/12-photo (2).webp",
      "images/projects-by-name/interior/مطبخ -  الشروق/12-photo (3).webp"
    ],
    "video": null,
    "excerpt": "تصميم مطبخ كلاسيكى يركّز على العملية في التوزيع، مع وحدات تخزين مدروسة وخامات سهلة الصيانة.",
    "description": "تصميم مطبخ كلاسيكى يركّز على العملية في التوزيع، مع وحدات تخزين مدروسة وخامات سهلة الصيانة.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطابخ"
    ],
    "featured": false
  },
  {
    "id": "مطبخ-صغير-d985d8b7",
    "discipline": "interior",
    "category": "",
    "title": "مطبخ صغير",
    "location": "",
    "area": null,
    "year": "",
    "cover": "images/projects-by-name/interior/مطبخ صغير/01-cover.webp",
    "before": null,
    "gallery": [],
    "video": null,
    "excerpt": "مشروع مطبخ صغير",
    "description": "مشروع مطبخ صغير.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "مطبخ-عصري-d985d8b7",
    "discipline": "interior",
    "category": "مطابخ",
    "title": "مطبخ عصري",
    "location": "",
    "area": null,
    "year": "2024",
    "cover": "images/projects-by-name/interior/مطبخ عصري/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مطبخ عصري/13-photo.webp",
      "images/projects-by-name/interior/مطبخ عصري/15-photo.webp"
    ],
    "video": null,
    "excerpt": "تصميم مطبخ عصري يركّز على العملية في التوزيع، مع وحدات تخزين مدروسة وخامات سهلة الصيانة.",
    "description": "تصميم مطبخ عصري يركّز على العملية في التوزيع، مع وحدات تخزين مدروسة وخامات سهلة الصيانة.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطابخ"
    ],
    "featured": false
  },
  {
    "id": "مطبخ-كلاسيكى-d985d8b7",
    "discipline": "interior",
    "category": "مطابخ",
    "title": "مطبخ كلاسيكى",
    "location": "",
    "area": null,
    "year": "2022",
    "cover": "images/projects-by-name/interior/مطبخ كلاسيكي/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مطبخ كلاسيكي/08-photo.webp",
      "images/projects-by-name/interior/مطبخ كلاسيكي/17-photo.webp"
    ],
    "video": null,
    "excerpt": "تصميم مطبخ كلاسيكى يركّز على العملية في التوزيع، مع وحدات تخزين مدروسة وخامات سهلة الصيانة.",
    "description": "تصميم مطبخ كلاسيكى يركّز على العملية في التوزيع، مع وحدات تخزين مدروسة وخامات سهلة الصيانة.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطابخ"
    ],
    "featured": false
  },
  {
    "id": "مطبخ-مودرن-d985d8b7",
    "discipline": "interior",
    "category": "مطابخ",
    "title": "مطبخ مودرن",
    "location": "",
    "area": null,
    "year": "2024",
    "cover": "images/projects-by-name/interior/مطبخ مودرن/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مطبخ مودرن/05-photo.webp",
      "images/projects-by-name/interior/مطبخ مودرن/06-photo.webp"
    ],
    "video": null,
    "excerpt": "تصميم مطبخ بطابع مودرن، بخطوط بسيطة ووحدات عملية تناسب الاستخدام اليومي.",
    "description": "تصميم مطبخ بطابع مودرن، بخطوط بسيطة ووحدات عملية تناسب الاستخدام اليومي.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطابخ",
      "Modern Kitchen"
    ],
    "featured": false
  },
  {
    "id": "مطبخ-مودرن-d985d8b7",
    "discipline": "interior",
    "category": "مطابخ",
    "title": "مطبخ مودرن",
    "location": "الشروق",
    "area": null,
    "year": "2026",
    "cover": "images/projects-by-name/interior/مطبخ نيو كلاسيكي/01-cover.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مطبخ نيو كلاسيكي/12-photo.webp"
    ],
    "video": null,
    "excerpt": "تصميم مطبخ نيو كلاسيك بخطوط بسيطة ووحدات عملية تناسب الاستخدام اليومي.",
    "description": "تصميم مطبخ نيو كلاسيك بخطوط بسيطة ووحدات عملية تناسب الاستخدام اليومي.",
    "idea": "",
    "materials": [],
    "tags": [
      "مطابخ",
      "Modern Kitchen"
    ],
    "featured": false
  },
  {
    "id": "معرض-النخبة-للسيارات-d985d8b9",
    "discipline": "interior",
    "category": "معارض",
    "title": "معرض النخبة للسيارات",
    "location": "السعوديه",
    "area": "80 م²",
    "year": "2025",
    "cover": "images/projects-by-name/interior/معرض النخبة  للسيارات السعوديه/معرض النخبة  السيارات (1) السعوديه.webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/معرض النخبة  للسيارات السعوديه/معرض النخبة  السيارات (2) السعوديه.webp"
    ],
    "video": null,
    "excerpt": "مشروع معرض النخبة للسيارات",
    "description": "مشروع معرض النخبة للسيارات.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "مكتب-اداري-d985d983",
    "discipline": "interior",
    "category": "مكاتب ادارية",
    "title": "مكتب اداري",
    "location": "الحي السابع مدينة نصر",
    "area": "35م²",
    "year": "2024",
    "cover": "images/projects-by-name/interior/مكتب اداري - الحي السابع/مكتب اداري الحي السابع (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مكتب اداري - الحي السابع/مكتب اداري الحي السابع (2).webp",
      "images/projects-by-name/interior/مكتب اداري - الحي السابع/مكتب اداري الحي السابع (3).webp"
    ],
    "video": null,
    "excerpt": "مشروع مكتب اداري",
    "description": "مشروع مكتب اداري.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  },
  {
    "id": "مكتب-حسابات-d985d983",
    "discipline": "interior",
    "category": "مكاتب ادارية",
    "title": "مكتب حسابات",
    "location": "مدينة نصر",
    "area": "30م²",
    "year": "2022",
    "cover": "images/projects-by-name/interior/مكتب حسابات-  مدينة نصر/مكتب حسابات مدينة نصر (1).webp",
    "before": null,
    "gallery": [
      "images/projects-by-name/interior/مكتب حسابات-  مدينة نصر/مكتب حسابات مدينة نصر (2).webp",
      "images/projects-by-name/interior/مكتب حسابات-  مدينة نصر/مكتب حسابات مدينة نصر (3).webp",
      "images/projects-by-name/interior/مكتب حسابات-  مدينة نصر/مكتب حسابات مدينة نصر (4).webp"
    ],
    "video": null,
    "excerpt": "مشروع مكتب حسابات",
    "description": "مشروع مكتب حسابات.",
    "idea": "",
    "materials": [],
    "tags": [],
    "featured": false
  }
];
const projectsData = PROJECTS_FALLBACK;
